# Site
color-scheme: auto

# Personal Info
name: Abdul Malek
title: Senior Software Engineer
email: me@almk.dev
phone: (646) 552-1769
location: New York, NY

# Social Links
github: almk-dev
linkedin: almk
resume: assets/resume.pdf

content:
    - section-title: SKILLS
      text-only: true
      content: |
          **Languages**  | Go, Python, JavaScript, Java, C++, x86, Lisp/Scheme, Bash
          **Tools**      | Linux, Git, AWS, FastAPI, Django, React, CSS, PostgreSQL, NoSQL, PySpark, Airflow, OpenGL, LWJGL
          **Experience** | distributed systems, web, security/crypto, financial systems, robotics, graphics, various math

    - section-title: WORK
      text-only: false
      content:
        - title: Alpaca
          sub-title: Senior Software Engineer
          fill_1: New York, NY
          fill_2: Oct. 2023 - Present
          description: Working on payments and treasury services

# TODO
# - cleaning pass
# - consider doing home page menu and multiple pages, including a detail/info page
# - consider changing spacing to use padding instead of bootstap col-1
# - double check content for errors
# - Fix line break issue with many slashes (fix gyro-scope)
# - make sure `display` attribute is reset to default and not just `inline`
# - Change all double quotes to single quotes (or no quotes?)
# - look over all files a final time to check style and consistency
# - remove/add unnecessary/necessary Liquid whitespace strips
# - restructure icons/button light/dark things into a central one
# - understand and clean up button.scss
# - consider box shadow for location box
# - incorporate more of the scss features
# - consider a light/dark toggle button
# - figure out how to prevent line breaks when printing
