info:
  name: Abdul Malek
  title: Software Engineer
  location: New York, NY

links:
  github: almk-dev
  linkedin: almk
  email: me@almk.dev

content:
  work:
    company: Octane Lending
    title: Software Engineer
    division: Scalability
    notes:
      - Designed and built system 01
      - Designed and built system 02
      - Designed and built system 03

  skills:
    - heading: Languages
      items:
        - Python
        - JavaScript
        - Java
        - C
        - C++
        - Haskell
        - Go
        - x86
        - Lisp/Scheme
        - Bash

    - heading: Tools
      items: 
        - Linux
        - Git
        - AWS
        - Django
        - FastAPI
        - Express
        - React,
        - Vue
        - PostgreSQL
        - MongoDB
        - DynamoDB
        - OpenGL
        - LWJGL
    
    - heading: Experience
      items:
        - distributed systems
        - microservices
        - web
        - security/crypto
        - natural language processing
        - graphics
        - robotics
        - various math

# TODO
# - Add a light/dark toggle
