name:
  first: Abdul
  last: Malek
location:
  city: New York
  state: NY

skills:
  languages:
    - Python
    - Go
    - JavaScript
    - Java
    - Scala
    - C++
    - x86
    - Lisp/Scheme
    - Bash
  tools:
    - Linux
    - Git
    - AWS
    - FastAPI
    - Django
    - React
    - CSS
    - PostgreSQL
    - NoSQL
    - PySpark
    - Airflow
    - OpenGL
    - LWJGL
  experience:
    - distributed systems
    - web
    - financial systems
    - security
    - crypto
    - operating systems
    - graphics
    - various math
work:
  position: Senior Software Engineer
  company:  Alpaca

links:
  github: almk-dev
  linkedin: almk
  email: me@almk.dev

# TODO
# - Add a light/dark toggle
