info:
  name: Abdul Malek
  title: Senior Software Engineer
  location: New York, NY

links:
  github: almk-dev
  linkedin: almk
  email: me@almk.dev

content:
  work:
    company: Octane Lending
    title: Software Engineer
    division: Scalability
    notes:
      - Designed and built system 01
      - Designed and built system 02
      - Designed and built system 03

  skills:
    - heading: Languages
      items:
        - Python
        - JavaScript
        - Java
        - C++
        - Go
        - x86
        - Lisp/Scheme
        - Bash

    - heading: Tools
      items: 
        - Linux
        - Git
        - AWS
        - FastAPI
        - Django
        - React,
        - CSS
        - PostgreSQL
        - NoSQL
        - PySpark
        - Airflow
        - OpenGL
        - LWJGL
    
    - heading: Experience
      items:
        - distributed systems
        - web
        - security/crypto
        - financial systems
        - robotics
        - graphics
        - various math

# TODO
# - Add a light/dark toggle
